import React from "react";
import { Briefcase, Eye, Users, Shield, User, HeartHandshake, Calendar, BookOpen, Compass, MapPin, Sparkles } from "lucide-react";

export const especialistasContent = {
  hero: {
    badge: {
      text: "Red Profesional de Bienestar",
      icon: <Briefcase className="h-4 w-4" />,
      variant: "pink" as const,
    },
    title: (
      <>
        Lleva tu conocimiento a una{" "}
        <span className="text-luminus-blue">
          red de personas
        </span>{" "}
        que buscan bienestar, claridad y transformación
      </>
    ),
    subtitle: "LUMINUS conecta a especialistas, profesionales y facilitadores con personas interesadas en bienestar, desarrollo personal, salud complementaria y vida consciente.\n\nSer Especialista LUMINUS te permite construir presencia dentro de la plataforma, mostrar tu enfoque profesional y ser descubierto por usuarios que buscan acompañamiento, recursos o servicios vinculados a tu área de experiencia.",
    primaryCta: {
      text: "Registrarme como primer paso",
      link: "https://app.luminuslatam.com/auth/registrarse",
    },
    secondaryCta: {
      text: "Conocer planes para especialistas",
      link: "#planes-especialistas",
    },
    microcopy: "*El primer paso para ser Especialista LUMINUS es crear tu cuenta dentro de la plataforma. La aprobación como especialista está sujeta a revisión.*",
    image: {
      src: "/experts-illustration.png",
      alt: "LUMINUS Professional & Specialists Wellness Network",
    },
    bgGlow: "from-luminus-pink/5 via-luminus-lime/5",
    imageBg: "shadow-bold-lg transition-transform duration-300 hover:rotate-1",
    borderBottom: true,
  },
  benefits: {
    title: "Un espacio para profesionales que quieren ampliar su impacto",
    subtitle: "En LUMINUS, los especialistas pueden presentar su trabajo, compartir conocimiento y conectar con una audiencia afín que ya está explorando nuevas formas de vivir con más equilibrio, propósito y bienestar.",
    items: [
      {
        title: "Más visibilidad para tu práctica",
        description: "Presenta tu enfoque, experiencia, servicios y áreas de trabajo dentro de una red diseñada para que las personas puedan descubrir profesionales alineados con sus búsquedas.",
        icon: <Eye className="h-6 w-6 text-black" />,
        cardClass: "bg-luminus-pink/15 hover:bg-luminus-pink/20 shadow-bold-pink",
        iconBg: "bg-luminus-pink",
      },
      {
        title: "Conexión con personas interesadas",
        description: "Llega a usuarios que ya forman parte de LUMINUS y que buscan orientación, recursos, sesiones o procesos para acompañar su camino personal.",
        icon: <Users className="h-6 w-6 text-black" />,
        cardClass: "bg-luminus-orange/15 hover:bg-luminus-orange/20 shadow-bold-orange",
        iconBg: "bg-luminus-orange",
      },
      {
        title: "Un entorno profesional y cuidado",
        description: "Forma parte de una plataforma que prioriza la confianza, la claridad de la información y la calidad de las conexiones entre usuarios y especialistas.",
        icon: <Shield className="h-6 w-6 text-black" />,
        cardClass: "bg-luminus-lime/15 hover:bg-luminus-lime/20 shadow-bold-lime",
        iconBg: "bg-luminus-lime",
      },
    ],
  },
  participation: {
    title: "Dos formas de participar como especialista",
    subtitle: "Elige el nivel de presencia y herramientas que mejor se adapte al momento de tu práctica profesional.",
    items: [
      {
        title: "Especialista LUMINUS",
        priceText: "Incluido en la membresía base",
        priceDetail: "USD 5/mes",
        description: "La membresía base de LUMINUS permite aplicar para formar parte del panel de especialistas. Si el perfil cumple con los requisitos de la plataforma, el especialista puede aparecer dentro de la red y ser descubierto por usuarios interesados en su área de trabajo.",
        inclusions: [
          "Acceso a la comunidad LUMINUS.",
          "Posibilidad de aplicar como Especialista LUMINUS.",
          "Revisión del perfil profesional por parte del equipo.",
          "Presencia en el panel de especialistas, sujeto a aprobación.",
          "Perfil profesional con especialidad, enfoque y experiencia.",
          "Posibilidad de ser contactado por usuarios de la plataforma.",
        ],
        note: "La aprobación como especialista no es automática. LUMINUS revisa los perfiles para cuidar la calidad, coherencia y confianza de la red.",
        ctaText: "Crear mi cuenta",
        ctaLink: "https://app.luminuslatam.com/auth/registrarse",
        badgeText: "Membresía Base",
        badgeBg: "bg-luminus-lime",
        cardBg: "bg-white border-2 border-black shadow-bold hover:shadow-bold-lg transition-all duration-150",
      },
      {
        title: "Especialista Plus",
        priceText: "USD 20/mes",
        priceDetail: "o USD 200/año con descuento",
        description: "Especialista Plus está pensado para profesionales que quieren usar LUMINUS como un canal más activo de visibilidad, contenido, comunidad y conexión con potenciales usuarios interesados en sus servicios.",
        inclusions: [
          "Sesiones introductorias gratuitas de 15 minutos para usuarios con suscripción activa.",
          "Publicación de cursos, recursos, talleres o materiales para la comunidad.",
          "Posibilidad de crear o participar en Espacios LUMINUS.",
          "Presencia destacada en el Mapa LUMINUS.",
          "Inclusión de clínicas, consultorios o espacios físicos asociados.",
          "Mayor visibilidad dentro de la plataforma.",
          "Acceso a nuevas funcionalidades para especialistas a medida que se vayan implementando.",
          "Herramientas para presentar tu propuesta profesional y conectar con personas afines.",
        ],
        note: "La opción anual de USD 200 incluye 2 meses bonificados sin costo adicional.",
        ctaText: "Activar Especialista Plus",
        ctaLink: "https://app.luminuslatam.com/auth/registrarse",
        badgeText: "Recomendado",
        badgeBg: "bg-luminus-orange text-white",
        isPopular: true,
        cardBg: "bg-luminus-orange/10 border-2 border-black shadow-bold-lg scale-[1.01] hover:-translate-y-1 transition-all duration-150 relative",
      },
    ],
  },
  introSessions: {
    title: "Sesiones introductorias de 15 minutos",
    subtitle: "Los Especialistas Plus podrán ofrecer sesiones introductorias de 15 minutos sin costo adicional para usuarios con suscripción activa en LUMINUS.",
    paragraphs: [
      "Estas sesiones están pensadas como un primer espacio de conexión. Permiten que el usuario conozca el enfoque del especialista, comparta brevemente su situación o interés, y evalúe si desea avanzar con un proceso, tratamiento, sesión paga, programa o servicio profesional ofrecido directamente por el especialista.",
      "Para el especialista, estas sesiones funcionan como una oportunidad de llegar a personas interesadas, generar confianza inicial y presentar su forma de trabajo de manera clara y cercana.",
      "LUMINUS facilita el contacto inicial entre usuarios y especialistas, pero no interviene en la relación profesional posterior, contratación, pago, prestación del servicio, resultados ni acuerdos particulares entre las partes.",
    ],
    ctaText: "Ofrecer sesiones introductorias",
    ctaLink: "https://app.luminuslatam.com/auth/registrarse",
  },
  features: {
    title: "Funciones pensadas para especialistas del bienestar",
    subtitle: "LUMINUS ofrece herramientas para que los profesionales puedan mostrarse, conectar, compartir contenido y acercar su propuesta a personas interesadas en bienestar y desarrollo humano.",
    items: [
      {
        title: "Perfil profesional",
        description: "Presenta quién eres, tu especialidad, tu enfoque, tus áreas de trabajo y la forma en que acompañas a las personas.",
        ctaText: "Crear mi perfil",
        ctaLink: "https://app.luminuslatam.com/auth/registrarse",
        icon: <User className="h-6 w-6" />,
        accentBgClass: "bg-luminus-blue text-white",
      },
      {
        title: "Conexión con personas",
        description: "Permite que los usuarios conozcan tu perfil, exploren tu propuesta y te contacten cuando sientan que tu enfoque puede acompañar su proceso.",
        ctaText: "Conectar con personas",
        ctaLink: "https://app.luminuslatam.com/auth/registrarse",
        icon: <HeartHandshake className="h-6 w-6" />,
        accentBgClass: "bg-luminus-orange text-black",
      },
      {
        title: "Sesiones y servicios",
        description: "Ofrece sesiones introductorias, presenta tus servicios y facilita una primera conversación con usuarios interesados en tu trabajo.",
        ctaText: "Mostrar servicios",
        ctaLink: "https://app.luminuslatam.com/auth/registrarse",
        icon: <Calendar className="h-6 w-6" />,
        accentBgClass: "bg-luminus-lime text-black",
      },
      {
        title: "Cursos y recursos",
        description: "Comparte conocimiento a través de contenidos, recursos, cursos o materiales que ayuden a la comunidad a aprender, reflexionar y avanzar.",
        ctaText: "Compartir recursos",
        ctaLink: "https://app.luminuslatam.com/auth/registrarse",
        icon: <BookOpen className="h-6 w-6" />,
        accentBgClass: "bg-luminus-pink text-black",
      },
      {
        title: "Espacios LUMINUS",
        description: "Crea o participa en espacios donde puedas compartir contenido relevante, abrir conversaciones, reunir personas afines e invitar a experiencias o eventos.",
        ctaText: "Crear un espacio",
        ctaLink: "https://app.luminuslatam.com/auth/registrarse",
        icon: <Compass className="h-6 w-6" />,
        accentBgClass: "bg-luminus-blue text-white",
      },
      {
        title: "Mapa LUMINUS",
        description: "Forma parte del Mapa LUMINUS para que las personas puedan descubrir especialistas, clínicas, consultorios y espacios de bienestar en su ciudad o en LATAM.",
        ctaText: "Aparecer en el mapa",
        ctaLink: "https://app.luminuslatam.com/auth/registrarse",
        icon: <MapPin className="h-6 w-6" />,
        accentBgClass: "bg-luminus-orange text-black",
      },
    ],
  },
  independence: {
    title: "Una experiencia pensada para profesionales independientes",
    paragraphs: [
      "LUMINUS no reemplaza tu práctica profesional ni interfiere en la forma en que trabajas. La plataforma funciona como un canal de visibilidad, conexión y descubrimiento.",
      "Tú mantienes tu independencia profesional, defines tu enfoque, tus servicios, tus condiciones y la forma en que decides acompañar a cada persona.",
      "LUMINUS te ayuda a estar presente dentro de una red de personas que buscan bienestar, conocimiento y acompañamiento confiable.",
    ],
  },
  pricing: {
    title: "Planes para especialistas",
    subtitle: "Encuentra el plan ideal para presentar tu práctica profesional y conectar con la comunidad.",
    plans: [
      {
        name: "Membresía Base LUMINUS",
        price: "USD 5",
        billing: "/mes",
        trialBadge: "Membresía Base",
        description: "Para personas que quieren formar parte de LUMINUS y, si cumplen con los requisitos de la plataforma, aplicar para aparecer como especialistas dentro de la red.",
        ctaText: "Registrarme con membresía base",
        ctaLink: "https://app.luminuslatam.com/auth/registrarse",
        disclaimer: "La aprobación del perfil está sujeta a revisión del equipo.",
        inclusions: [
          "Acceso a la comunidad.",
          "Posibilidad de aplicar como Especialista LUMINUS.",
          "Perfil profesional sujeto a aprobación.",
          "Presencia en el panel de especialistas.",
          "Posibilidad de ser descubierto y contactado por usuarios.",
        ],
      },
      {
        name: "Especialista Plus",
        price: "USD 20",
        billing: "/mes",
        trialBadge: "3 meses sin costo",
        discountBadge: "Ahorra con pago anual",
        description: "Para especialistas que quieren ampliar su presencia, ofrecer sesiones introductorias, publicar contenido, crear espacios y activar nuevas oportunidades de conexión dentro de LUMINUS.",
        ctaText: "Elegir Especialista Plus",
        ctaLink: "https://app.luminuslatam.com/auth/registrarse",
        disclaimer: "USD 200/año — 2 meses sin costo en suscripción anual.",
        isPopular: true,
        inclusions: [
          "Todo lo incluido en la membresía base.",
          "Sesiones introductorias gratuitas de 15 minutos.",
          "Cursos, recursos y materiales.",
          "Espacios LUMINUS.",
          "Mapa LUMINUS.",
          "Clínicas, consultorios o espacios asociados.",
          "Mayor visibilidad dentro de la plataforma.",
          "Nuevas funcionalidades para especialistas.",
        ],
      },
    ],
  },
  stepsSection: {
    title: "Cómo funciona",
    subtitle: "Comienza tu camino como Especialista LUMINUS siguiendo estos sencillos pasos.",
    ctaText: "Registrarme como primer paso",
    ctaLink: "https://app.luminuslatam.com/auth/registrarse",
    steps: [
      {
        num: "01",
        title: "Crea tu cuenta",
        description: "Regístrate en LUMINUS y activa tu membresía base para ingresar a la red.",
        numColor: "text-luminus-blue",
        badgeBg: "bg-luminus-blue text-white",
        shadowColor: "shadow-bold-blue",
      },
      {
        num: "02",
        title: "Completa tu perfil",
        description: "Presenta tu experiencia, especialidad, enfoque, áreas de acompañamiento y propuesta profesional.",
        numColor: "text-luminus-orange",
        badgeBg: "bg-luminus-orange text-black",
        shadowColor: "shadow-bold-orange",
      },
      {
        num: "03",
        title: "Aplica como especialista",
        description: "El equipo de LUMINUS revisará tu perfil para validar que cumpla con los criterios de la plataforma.",
        numColor: "text-luminus-lime",
        badgeBg: "bg-luminus-lime text-black",
        shadowColor: "shadow-bold-lime",
      },
      {
        num: "04",
        title: "Activa tu presencia",
        description: "Si tu perfil es aprobado, podrás aparecer en el panel de especialistas y ser descubierto por usuarios.",
        numColor: "text-luminus-pink",
        badgeBg: "bg-luminus-pink text-black",
        shadowColor: "shadow-bold-pink",
      },
      {
        num: "05",
        title: "Crece con Especialista Plus",
        description: "Si quieres ofrecer sesiones introductorias, publicar cursos, crear espacios o aparecer en el mapa, podrás activar Especialista Plus.",
        numColor: "text-luminus-blue",
        badgeBg: "bg-luminus-blue text-white",
        shadowColor: "shadow-bold-blue",
      },
    ],
  },
  trust: {
    title: "Empieza sin compromiso",
    description: "Durante los primeros 3 meses podrás explorar LUMINUS sin costo. No se solicitará ningún pago al registrarte y te avisaremos antes de que finalice el período de acceso sin costo para que puedas decidir si deseas continuar.",
    assurances: [
      "No se solicitan datos de pago al crear tu cuenta.",
      "Acceso sin costo durante los primeros 3 meses.",
      "Podrás elegir si continuar o no antes de que termine el período gratuito.",
      "La aprobación como especialista está sujeta a revisión.",
    ],
  },
  finalCta: {
    icon: <Sparkles className="h-5 w-5 text-luminus-orange" />,
    title: "Empieza tu camino como Especialista LUMINUS",
    subtitle: "Crea tu cuenta y da el primer paso para formar parte de una red que conecta bienestar, conocimiento y propósito.\n\nLuego del registro podrás completar tu perfil, aplicar como especialista y acceder a las funciones disponibles según tu plan.",
    ctaText: "Registrarme como primer paso",
    ctaLink: "https://app.luminuslatam.com/auth/registrarse",
    secondaryCtaText: "Ver Especialista Plus",
    secondaryCtaLink: "#planes-especialistas",
    microcopy: "Luego del registro podrás completar tu perfil, aplicar como especialista y acceder a las funciones disponibles según tu plan.",
    bgGlow: "from-luminus-orange/5 to-transparent",
    cardBg: "bg-luminus-orange/15",
    iconColor: "text-luminus-orange",
  },
  legalFootnote: {
    text: "LUMINUS actúa únicamente como una plataforma de conexión entre usuarios y especialistas independientes. La participación como especialista está sujeta a criterios de revisión, admisión y permanencia definidos por LUMINUS. Las sesiones, servicios, tratamientos, programas, pagos, resultados o acuerdos posteriores entre usuarios y especialistas son responsabilidad exclusiva de las partes involucradas.",
  },
};
