import React from "react";
import { Briefcase, Eye, Users, Shield, User, HeartHandshake, Calendar, BookOpen, Compass, MapPin, Sparkles } from "lucide-react";

export const especialistasContent = {
  hero: {
    badge: {
      text: "Para profesionales del bienestar",
      icon: <Briefcase className="h-4 w-4" />,
      variant: "pink" as const,
    },
    title: (
      <>
        Lleva tu conocimiento a una{" "}
        <span className="text-luminus-blue">
          red de personas
        </span>{" "}
        que buscan bienestar y acompañamiento
      </>
    ),
    subtitle: "Forma parte de una red creada para conectar especialistas del bienestar con personas interesadas en vivir con más claridad, equilibrio y propósito.\n\nPresenta tu enfoque, da visibilidad a tu práctica y permite que más personas descubran tu trabajo.",
    primaryCta: {
      text: "Registrarme como especialista",
      link: "https://app.luminuslatam.com/auth/registrarse",
    },
    secondaryCta: {
      text: "Conocer cómo funciona",
      link: "#como-funciona",
    },
    microcopy: "El primer paso es crear tu cuenta. La participación como especialista está sujeta a revisión.",
    image: {
      src: "/experts-illustration.png",
      alt: "LUMINUS Professional & Specialists Wellness Network",
    },
    bgGlow: "from-luminus-pink/5 via-luminus-lime/5",
    imageBg: "shadow-bold-lg transition-transform duration-300 hover:rotate-1",
    borderBottom: true,
  },
  benefits: {
    title: "Un espacio para ampliar tu impacto profesional",
    subtitle: "LUMINUS acerca tu trabajo a personas que ya están explorando temas de bienestar, desarrollo personal y acompañamiento profesional.",
    items: [
      {
        title: "Más visibilidad",
        description: "Presenta tu perfil, especialidad, enfoque y servicios dentro de una red orientada al bienestar.",
        icon: <Eye className="h-6 w-6 text-black" />,
        cardClass: "bg-luminus-pink/15 hover:bg-luminus-pink/20 shadow-bold-pink",
        iconBg: "bg-luminus-pink",
      },
      {
        title: "Mejores conexiones",
        description: "Llega a personas interesadas en orientación, sesiones, recursos o procesos de acompañamiento.",
        icon: <Users className="h-6 w-6 text-black" />,
        cardClass: "bg-luminus-orange/15 hover:bg-luminus-orange/20 shadow-bold-orange",
        iconBg: "bg-luminus-orange",
      },
      {
        title: "Un entorno cuidado",
        description: "Forma parte de una red que prioriza claridad, confianza y calidad en cada conexión.",
        icon: <Shield className="h-6 w-6 text-black" />,
        cardClass: "bg-luminus-lime/15 hover:bg-luminus-lime/20 shadow-bold-lime",
        iconBg: "bg-luminus-lime",
      },
    ],
  },
  participation: {
    title: "Dos formas de participar como especialista",
    subtitle: "Puedes comenzar con una presencia básica dentro de la red o activar herramientas adicionales para aumentar tu visibilidad y compartir más valor.",
    items: [
      {
        title: "Especialista",
        priceText: "Incluido en la membresía base",
        priceDetail: "",
        description: "Para profesionales que quieren crear su perfil, aplicar al panel de especialistas y ser descubiertos dentro de la red.",
        inclusions: [
          "Acceso a la comunidad.",
          "Aplicación como especialista.",
          "Revisión del perfil profesional.",
          "Perfil con especialidad, enfoque y experiencia.",
          "Presencia en el panel, sujeta a aprobación.",
          "Posibilidad de ser contactado por personas interesadas.",
        ],
        note: "La aprobación como especialista no es automática. El equipo revisa cada perfil para cuidar la calidad de la red.",
        ctaText: "Crear mi cuenta",
        ctaLink: "https://app.luminuslatam.com/auth/registrarse",
        badgeText: "Especialista Base",
        badgeBg: "bg-luminus-lime",
        cardBg: "bg-white border-2 border-black shadow-bold hover:shadow-bold-lg transition-all duration-150",
      },
      {
        title: "Especialista Plus",
        priceText: "USD 20/mes",
        priceDetail: "o USD 200/año",
        description: "Para especialistas que quieren ampliar su presencia, compartir contenidos y activar nuevas oportunidades de conexión.",
        inclusions: [
          "Todo lo incluido en Especialista.",
          "Sesiones introductorias de 15 minutos.",
          "Publicación de cursos, recursos o materiales.",
          "Participación o creación de espacios.",
          "Presencia destacada en el mapa.",
          "Inclusión de clínicas, consultorios o espacios físicos.",
          "Mayor visibilidad dentro de la plataforma.",
        ],
        note: "La opción anual incluye 2 meses bonificados frente al pago mensual.",
        ctaText: "Activar Especialista Plus",
        ctaLink: "https://app.luminuslatam.com/auth/registrarse",
        badgeText: "Más herramientas de visibilidad",
        badgeBg: "bg-luminus-orange text-white",
        isPopular: true,
        cardBg: "bg-luminus-orange/10 border-2 border-black shadow-bold-lg scale-[1.01] hover:-translate-y-1 transition-all duration-150 relative",
      },
    ],
  },
  introSessions: {
    title: "Sesiones introductorias de 15 minutos",
    subtitle: "Los especialistas Plus podrán ofrecer una primera conversación sin costo adicional para personas con suscripción activa.",
    paragraphs: [
      "Estas sesiones permiten que la persona conozca tu enfoque, comparta brevemente su necesidad y evalúe si quiere avanzar con un servicio, tratamiento, programa o proceso profesional contigo.",
      "LUMINUS facilita el contacto inicial, pero no interviene en acuerdos, pagos, servicios, resultados ni relaciones profesionales posteriores."
    ],
    ctaText: "Ofrecer sesiones introductorias",
    ctaLink: "https://app.luminuslatam.com/auth/registrarse",
  },
  features: {
    title: "Funciones pensadas para presentar mejor tu trabajo",
    subtitle: "Accede a herramientas para mostrar tu propuesta profesional, compartir contenido y conectar con personas interesadas en tu área de experiencia.",
    items: [
      {
        title: "Perfil profesional",
        description: "Comparte quién eres, tu especialidad, tu formación y tu forma de acompañar.",
        ctaText: "Crear mi perfil",
        ctaLink: "https://app.luminuslatam.com/auth/registrarse",
        icon: <User className="h-6 w-6" />,
        accentBgClass: "bg-luminus-blue text-white",
      },
      {
        title: "Primer contacto",
        description: "Permite que las personas conozcan tu perfil y te contacten desde la plataforma.",
        ctaText: "Habilitar contacto",
        ctaLink: "https://app.luminuslatam.com/auth/registrarse",
        icon: <HeartHandshake className="h-6 w-6" />,
        accentBgClass: "bg-luminus-orange text-black",
      },
      {
        title: "Sesiones y servicios",
        description: "Presenta tus servicios y ofrece sesiones introductorias para abrir nuevas conversaciones.",
        ctaText: "Ofrecer sesiones",
        ctaLink: "https://app.luminuslatam.com/auth/registrarse",
        icon: <Calendar className="h-6 w-6" />,
        accentBgClass: "bg-luminus-lime text-black",
      },
      {
        title: "Cursos y recursos",
        description: "Publica contenidos, materiales o recursos para aportar valor a la comunidad.",
        ctaText: "Publicar recursos",
        ctaLink: "https://app.luminuslatam.com/auth/registrarse",
        icon: <BookOpen className="h-6 w-6" />,
        accentBgClass: "bg-luminus-pink text-black",
      },
      {
        title: "Espacios",
        description: "Crea o participa en espacios de aprendizaje, conversación y encuentro.",
        ctaText: "Crear un espacio",
        ctaLink: "https://app.luminuslatam.com/auth/registrarse",
        icon: <Compass className="h-6 w-6" />,
        accentBgClass: "bg-luminus-blue text-white",
      },
      {
        title: "Mapa",
        description: "Haz visible tu presencia física, consultorio, clínica o espacio de bienestar.",
        ctaText: "Aparecer en el mapa",
        ctaLink: "https://app.luminuslatam.com/auth/registrarse",
        icon: <MapPin className="h-6 w-6" />,
        accentBgClass: "bg-luminus-orange text-black",
      },
    ],
  },
  independence: {
    title: "Tu práctica profesional sigue siendo tuya",
    paragraphs: [
      "LUMINUS funciona como un canal de visibilidad, conexión y descubrimiento. No define tu método, tus precios, tus servicios ni tus condiciones profesionales.",
      "Tú mantienes tu criterio, tu identidad y tu forma de trabajar."
    ],
  },
  pricing: {
    title: "Elige cómo quieres participar",
    subtitle: "Comienza aplicando como especialista desde la membresía base o activa Especialista Plus para acceder a más herramientas de visibilidad y conexión.",
    plans: [
      {
        name: "Especialista",
        price: "USD 5",
        billing: "/mes",
        trialBadge: "Incluido en la membresía base",
        description: "Para profesionales que quieren formar parte de la red y aplicar para aparecer dentro del panel de especialistas.",
        ctaText: "Registrarme con membresía base",
        ctaLink: "https://app.luminuslatam.com/auth/registrarse",
        disclaimer: "La aprobación del perfil está sujeta a revisión.",
        inclusions: [
          "Acceso a la comunidad.",
          "Aplicación como especialista.",
          "Perfil profesional sujeto a aprobación.",
          "Presencia en el panel.",
          "Posibilidad de ser descubierto y contactado.",
          "Acceso a contenidos y novedades.",
        ],
      },
      {
        name: "Especialista Plus",
        price: "USD 20",
        billing: "/mes",
        trialBadge: "3 meses sin costo",
        discountBadge: "2 meses bonificados en suscripción anual",
        description: "Para especialistas que quieren aumentar su presencia, compartir contenidos y activar nuevas formas de conexión.",
        ctaText: "Elegir Especialista Plus",
        ctaLink: "https://app.luminuslatam.com/auth/registrarse",
        disclaimer: "USD 200/año. La opción anual incluye 2 meses bonificados.",
        isPopular: true,
        inclusions: [
          "Todo lo incluido en Especialista.",
          "Sesiones introductorias de 15 minutos.",
          "Publicación de cursos, recursos y materiales.",
          "Participación o creación de espacios.",
          "Presencia destacada en el mapa.",
          "Clínicas, consultorios o espacios asociados.",
          "Mayor visibilidad en la plataforma.",
          "Acceso prioritario a nuevas funcionalidades.",
        ],
      },
    ],
  },
  stepsSection: {
    title: "Cómo empezar como especialista",
    subtitle: "El proceso está pensado para ser simple, claro y progresivo.",
    ctaText: "Registrarme como especialista",
    ctaLink: "https://app.luminuslatam.com/auth/registrarse",
    steps: [
      {
        num: "01",
        title: "Crea tu cuenta",
        description: "Regístrate en la plataforma e ingresa a la red.",
        numColor: "text-luminus-blue",
        badgeBg: "bg-luminus-blue text-white",
        shadowColor: "shadow-bold-blue",
      },
      {
        num: "02",
        title: "Completa tu perfil",
        description: "Presenta tu experiencia, especialidad, enfoque y servicios.",
        numColor: "text-luminus-orange",
        badgeBg: "bg-luminus-orange text-black",
        shadowColor: "shadow-bold-orange",
      },
      {
        num: "03",
        title: "Aplica como especialista",
        description: "El equipo revisará tu perfil antes de aprobar tu participación.",
        numColor: "text-luminus-lime",
        badgeBg: "bg-luminus-lime text-black",
        shadowColor: "shadow-bold-lime",
      },
      {
        num: "04",
        title: "Activa tu presencia",
        description: "Si tu perfil es aprobado, podrás aparecer en el panel de especialistas.",
        numColor: "text-luminus-pink",
        badgeBg: "bg-luminus-pink text-black",
        shadowColor: "shadow-bold-pink",
      },
      {
        num: "05",
        title: "Potencia tu alcance",
        description: "Con Especialista Plus podrás acceder a más herramientas de visibilidad y conexión.",
        numColor: "text-luminus-blue",
        badgeBg: "bg-luminus-blue text-white",
        shadowColor: "shadow-bold-blue",
      },
    ],
  },
  trust: {
    title: "Empieza sin compromiso",
    description: "Durante los primeros 3 meses podrás explorar LUMINUS sin costo. No se solicitan datos de pago al registrarte y te avisaremos antes de que finalice este período.",
    assurances: [
      "3 meses de acceso sin costo.",
      "Sin datos de pago al crear tu cuenta.",
      "Posibilidad de aplicar como especialista.",
      "Aprobación sujeta a revisión.",
      "Libertad para decidir si quieres continuar.",
    ],
  },
  finalCta: {
    icon: <Sparkles className="h-5 w-5 text-luminus-orange" />,
    title: "Da el primer paso para formar parte de una red de bienestar en crecimiento",
    subtitle: "Crea tu cuenta, completa tu perfil y aplica para formar parte del panel de especialistas. Si quieres ampliar tu presencia, podrás activar Especialista Plus y acceder a más herramientas para compartir tu trabajo.",
    ctaText: "Registrarme como especialista",
    ctaLink: "https://app.luminuslatam.com/auth/registrarse",
    secondaryCtaText: "Ver Especialista Plus",
    secondaryCtaLink: "#planes-especialistas",
    microcopy: "La participación como especialista está sujeta a revisión. Algunas funcionalidades estarán disponibles progresivamente.",
    bgGlow: "from-luminus-orange/5 to-transparent",
    cardBg: "bg-luminus-orange/15",
    iconColor: "text-luminus-orange",
  },
  legalFootnote: {
    text: "LUMINUS actúa como una plataforma de conexión entre personas y especialistas independientes. Las sesiones, servicios, tratamientos, pagos, resultados o acuerdos posteriores son responsabilidad exclusiva de las partes involucradas.",
  },
};
