name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Correr Tests
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # La versión de node de tu entorno actual

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar los tests
      run: npm run test:platform
